### ISSUE TITLE
About submenu runs off-screen

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/noh#483] opened 2019-08-22 14:58 UTC
On internal pages, such as play or section level pages, the about dropdown menu can run off the right edge of the window

**Comment by broadwell** [comment] 2019-08-22 16:18
Perhaps a fix for this would also address the more general tendency of the dropdown menus to overlap with the other headings -- the dropdown for `INTERMEDIA` often overlaps the P in `PLAYS`, the dropdown for `PLAYS` overlaps the E in `ELEMENTS`, etc.

**Comment by simonwiles** [comment] 2019-08-22 16:21
It's not obvious to me what a solution to that would look like -- do you have ideas?  More concerning to me (and much closer in terms of symptoms and possible solutions) is when the new "About" menu flows off the right-hand edge of the screen.  Whatever is done to address this issue directly (and it looks to me like we're going to have to bite the bullet and script this behaviour), we should take this into account in the process, I think.

**Comment by broadwell** [comment] 2019-08-22 16:27
Both complaints have the same root cause: that the spacing of the top-level menus is determined according to the contents of the heading (`INTERMEDIA`, `PLAYS`, etc.), and so when the drop-down menu items have text that is wider than the heading, (e.g., `TOOLS OF ANALYSIS`, `NOH AS INTERMEDIA` under `INTERMEDIA`), it causes an overlap with the next heading, or runs off the right-hand side of the page.
So one possible fix would be to have the parent headings inherit the width of their widest child, which hopefully(?) would look OK.

**Comment by simonwiles** [comment] 2019-08-22 16:30
Hmm, yeah, that could work for the overlapping issue you described -- might be worth looking at.  It's a quite different issue from tooltips flowing off-screen, but it may mitigate or completely alleviate the concern I described too.

**Comment by broadwell** [comment] 2019-08-22 17:34
This is only really an issue on L2, and can be addressed by adding 1.25rem of right-side padding to `header__nav`.
The more general problem of overlap between expanded menu items is discussed in #484.

**Comment by simonwiles** [comment] 2019-08-24 01:23
Closed by #493.

**Closed by simonwiles** 2019-08-24 01:23 UTC
Labels: bug, design
